export const COMPONENT_LIBRARY = {
  layout: {
    name: 'Layout',
    icon: '📦',
    components: [
      {
        id: 'container',
        name: 'Container',
        icon: '📦',
        preview: 'Basic container for grouping elements',
        defaultProps: {
          width: '100%',
          height: 'auto',
          padding: '16px',
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          border: '1px solid #e0e0e0',
        },
        children: [],
      },
      {
        id: 'section',
        name: 'Section',
        icon: '📄',
        preview: 'Full-width section with padding',
        defaultProps: {
          width: '100%',
          height: 'auto',
          padding: '32px 16px',
          display: 'flex',
          flexDirection: 'column',
          gap: '16px',
          backgroundColor: '#f5f5f5',
        },
        children: [],
      },
      {
        id: 'grid',
        name: 'Grid',
        icon: '⊞',
        preview: '3-column responsive grid layout',
        defaultProps: {
          width: '100%',
          height: 'auto',
          display: 'grid',
          gridTemplateColumns: 'repeat(3, 1fr)',
          gap: '16px',
          padding: '16px',
        },
        children: [],
      },
      {
        id: 'flex',
        name: 'Flex',
        icon: '↔️',
        preview: 'Flexible row layout with gap',
        defaultProps: {
          width: '100%',
          height: 'auto',
          display: 'flex',
          flexDirection: 'row',
          gap: '16px',
          padding: '16px',
          alignItems: 'center',
        },
        children: [],
      },
      {
        id: 'card',
        name: 'Card',
        icon: '🎴',
        preview: 'Elevated card with shadow',
        defaultProps: {
          width: '300px',
          height: 'auto',
          padding: '16px',
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
          border: 'none',
        },
        children: [],
      },
      {
        id: 'divider',
        name: 'Divider',
        icon: '─',
        preview: 'Horizontal line separator',
        defaultProps: {
          width: '100%',
          height: '1px',
          backgroundColor: '#e0e0e0',
          margin: '16px 0',
        },
        children: [],
      },
      {
        id: 'spacer',
        name: 'Spacer',
        icon: '⬜',
        preview: 'Empty space element',
        defaultProps: {
          width: '100%',
          height: '16px',
          backgroundColor: 'transparent',
        },
        children: [],
      },
    ],
  },

  inputs: {
    name: 'Inputs',
    icon: '⌨️',
    components: [
      {
        id: 'button',
        name: 'Primary Button',
        icon: '🔘',
        preview: 'Primary contained button',
        defaultProps: {
          text: 'Click me',
          padding: '10px 18px',
          backgroundColor: '#2563eb',
          color: '#ffffff',
          border: 'none',
          borderRadius: '12px',
          fontSize: '14px',
          fontWeight: '700',
          cursor: 'pointer',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'button-outlined',
        name: 'Outlined Button',
        icon: '⬜',
        preview: 'Secondary outlined button',
        defaultProps: {
          text: 'Secondary',
          padding: '10px 18px',
          backgroundColor: 'transparent',
          color: '#2563eb',
          border: '2px solid #2563eb',
          borderRadius: '12px',
          fontSize: '14px',
          fontWeight: '700',
          cursor: 'pointer',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'button-gradient',
        name: 'Gradient Button',
        icon: '🌈',
        preview: 'Gradient action button',
        defaultProps: {
          text: 'Launch',
          padding: '10px 18px',
          backgroundColor: 'linear-gradient(135deg, #4f46e5, #2563eb)',
          color: '#ffffff',
          border: 'none',
          borderRadius: '999px',
          fontSize: '14px',
          fontWeight: '700',
          cursor: 'pointer',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'button-icon',
        name: 'Icon Button',
        icon: '⭐',
        preview: 'Button with icon variant',
        defaultProps: {
          text: 'Favorite',
          padding: '10px 14px',
          backgroundColor: '#ffffff',
          color: '#111827',
          border: '1px solid #d1d5db',
          borderRadius: '999px',
          fontSize: '14px',
          fontWeight: '600',
          cursor: 'pointer',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'button-loading',
        name: 'Loading Button',
        icon: '⏳',
        preview: 'Button with loading state',
        defaultProps: {
          text: 'Loading...',
          padding: '10px 18px',
          backgroundColor: '#111827',
          color: '#ffffff',
          border: 'none',
          borderRadius: '12px',
          fontSize: '14px',
          fontWeight: '700',
          cursor: 'progress',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'input',
        name: 'Text Input',
        icon: '📝',
        preview: 'Text input field',
        defaultProps: {
          placeholder: 'Enter text...',
          width: '100%',
          height: '44px',
          padding: '12px 14px',
          border: '1px solid #d1d5db',
          borderRadius: '12px',
          fontSize: '14px',
        },
        children: [],
      },
      {
        id: 'password-input',
        name: 'Password Input',
        icon: '🔒',
        preview: 'Secure password field',
        defaultProps: {
          placeholder: 'Enter password...',
          width: '100%',
          height: '44px',
          padding: '12px 14px',
          border: '1px solid #d1d5db',
          borderRadius: '12px',
          fontSize: '14px',
        },
        children: [],
      },
      {
        id: 'textarea',
        name: 'Textarea',
        icon: '📋',
        preview: 'Multi-line text area',
        defaultProps: {
          placeholder: 'Write your message...',
          width: '100%',
          height: '140px',
          padding: '12px 14px',
          border: '1px solid #d1d5db',
          borderRadius: '12px',
          fontSize: '14px',
          fontFamily: 'inherit',
        },
        children: [],
      },
      {
        id: 'autocomplete',
        name: 'Autocomplete',
        icon: '🔍',
        preview: 'Search style input',
        defaultProps: {
          placeholder: 'Search...',
          width: '100%',
          height: '44px',
          padding: '12px 14px',
          border: '1px solid #d1d5db',
          borderRadius: '12px',
          fontSize: '14px',
          cursor: 'pointer',
        },
        children: [],
      },
      {
        id: 'select',
        name: 'Dropdown Select',
        icon: '▼',
        preview: 'Dropdown select',
        defaultProps: {
          width: '100%',
          height: '44px',
          padding: '12px 14px',
          border: '1px solid #d1d5db',
          borderRadius: '12px',
          fontSize: '14px',
          cursor: 'pointer',
        },
        children: [],
      },
    ],
  },

  content: {
    name: 'Content',
    icon: '📄',
    components: [
      {
        id: 'heading',
        name: 'Heading',
        icon: 'H',
        preview: 'Large heading text',
        defaultProps: {
          text: 'Heading',
          fontSize: '32px',
          fontWeight: '700',
          color: '#1a1a1a',
          marginBottom: '16px',
          width: '100%',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'subheading',
        name: 'Subheading',
        icon: 'h2',
        preview: 'Medium subheading',
        defaultProps: {
          text: 'Subheading',
          fontSize: '24px',
          fontWeight: '600',
          color: '#1a1a1a',
          marginBottom: '12px',
          width: '100%',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'paragraph',
        name: 'Paragraph',
        icon: '¶',
        preview: 'Body text paragraph',
        defaultProps: {
          text: 'This is a paragraph of text.',
          fontSize: '16px',
          color: '#666666',
          lineHeight: '1.5',
          marginBottom: '16px',
          width: '100%',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'label',
        name: 'Label',
        icon: '🏷️',
        preview: 'Form label text',
        defaultProps: {
          text: 'Label',
          fontSize: '14px',
          fontWeight: '500',
          color: '#1a1a1a',
          marginBottom: '8px',
          width: '100%',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'image',
        name: 'Image',
        icon: '🖼️',
        preview: 'Image element',
        defaultProps: {
          src: 'https://via.placeholder.com/300x200',
          width: '300px',
          height: '200px',
          borderRadius: '8px',
          objectFit: 'cover',
        },
        children: [],
      },
      {
        id: 'badge',
        name: 'Badge',
        icon: '🔴',
        preview: 'Small badge label',
        defaultProps: {
          text: 'Badge',
          padding: '4px 8px',
          backgroundColor: '#0066cc',
          color: '#ffffff',
          borderRadius: '12px',
          fontSize: '12px',
          fontWeight: '600',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'chip',
        name: 'Chip',
        icon: '🏷️',
        preview: 'Compact chip element',
        defaultProps: {
          text: 'Chip',
          padding: '6px 12px',
          backgroundColor: '#e0e0e0',
          color: '#1a1a1a',
          borderRadius: '16px',
          fontSize: '13px',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
      {
        id: 'link',
        name: 'Link',
        icon: '🔗',
        preview: 'Hyperlink text',
        defaultProps: {
          text: 'Link',
          fontSize: '14px',
          color: '#0066cc',
          textDecoration: 'underline',
          cursor: 'pointer',
          width: 'auto',
          height: 'auto',
        },
        children: [],
      },
    ],
  },

  navigation: {
    name: 'Navigation',
    icon: '🧭',
    components: [
      {
        id: 'navbar',
        name: 'Navbar',
        icon: '📍',
        preview: 'Top navigation bar',
        defaultProps: {
          width: '100%',
          height: '64px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '0 24px',
          backgroundColor: '#ffffff',
          borderBottom: '1px solid #e0e0e0',
        },
        children: [],
      },
      {
        id: 'breadcrumb',
        name: 'Breadcrumb',
        icon: '🔗',
        preview: 'Navigation breadcrumb',
        defaultProps: {
          width: '100%',
          height: 'auto',
          display: 'flex',
          gap: '8px',
          padding: '8px 0',
          fontSize: '14px',
        },
        children: [],
      },
      {
        id: 'tabs',
        name: 'Tabs',
        icon: '📑',
        preview: 'Tabbed navigation',
        defaultProps: {
          width: '100%',
          height: 'auto',
          display: 'flex',
          gap: '0',
          padding: '0',
          borderBottom: '1px solid #e0e0e0',
        },
        children: [],
      },
      {
        id: 'menu',
        name: 'Menu',
        icon: '☰',
        preview: 'Dropdown menu',
        defaultProps: {
          width: 'auto',
          height: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: '0',
          padding: '8px 0',
          backgroundColor: '#ffffff',
          borderRadius: '4px',
          boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
        },
        children: [],
      },
      {
        id: 'sidebar',
        name: 'Sidebar',
        icon: '◀',
        preview: 'Side navigation panel',
        defaultProps: {
          width: '250px',
          height: '100vh',
          display: 'flex',
          flexDirection: 'column',
          gap: '0',
          padding: '16px',
          backgroundColor: '#f5f5f5',
          borderRight: '1px solid #e0e0e0',
        },
        children: [],
      },
    ],
  },

  feedback: {
    name: 'Feedback',
    icon: '💬',
    components: [
      {
        id: 'alert',
        name: 'Alert',
        icon: '⚠️',
        preview: 'Alert message box',
        defaultProps: {
          text: 'Alert message',
          width: '100%',
          height: 'auto',
          padding: '12px 16px',
          backgroundColor: '#fff3cd',
          color: '#856404',
          borderRadius: '4px',
          border: '1px solid #ffeaa7',
          fontSize: '14px',
        },
        children: [],
      },
      {
        id: 'alert-success',
        name: 'Alert Success',
        icon: '✅',
        preview: 'Success alert message',
        defaultProps: {
          text: 'Success message',
          width: '100%',
          height: 'auto',
          padding: '12px 16px',
          backgroundColor: '#d4edda',
          color: '#155724',
          borderRadius: '4px',
          border: '1px solid #c3e6cb',
          fontSize: '14px',
        },
        children: [],
      },
      {
        id: 'alert-error',
        name: 'Alert Error',
        icon: '❌',
        preview: 'Error alert message',
        defaultProps: {
          text: 'Error message',
          width: '100%',
          height: 'auto',
          padding: '12px 16px',
          backgroundColor: '#f8d7da',
          color: '#721c24',
          borderRadius: '4px',
          border: '1px solid #f5c6cb',
          fontSize: '14px',
        },
        children: [],
      },
      {
        id: 'toast',
        name: 'Toast',
        icon: '🔔',
        preview: 'Toast notification',
        defaultProps: {
          text: 'Toast message',
          width: '300px',
          height: 'auto',
          padding: '12px 16px',
          backgroundColor: '#333333',
          color: '#ffffff',
          borderRadius: '4px',
          fontSize: '14px',
          boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
        },
        children: [],
      },
      {
        id: 'progress',
        name: 'Progress',
        icon: '📊',
        preview: 'Progress bar',
        defaultProps: {
          width: '100%',
          height: '4px',
          backgroundColor: '#e0e0e0',
          borderRadius: '2px',
        },
        children: [],
      },
      {
        id: 'spinner',
        name: 'Spinner',
        icon: '⏳',
        preview: 'Loading spinner',
        defaultProps: {
          width: '40px',
          height: '40px',
          borderRadius: '50%',
          border: '4px solid #e0e0e0',
          borderTop: '4px solid #0066cc',
        },
        children: [],
      },
    ],
  },

  advanced: {
    name: 'Advanced',
    icon: '⚙️',
    components: [
      {
        id: 'table',
        name: 'Table',
        icon: '📊',
        preview: 'Data table',
        defaultProps: {
          width: '100%',
          height: 'auto',
          border: '1px solid #e0e0e0',
          borderRadius: '4px',
          overflow: 'hidden',
        },
        children: [],
      },
      {
        id: 'form-group',
        name: 'Form Group',
        icon: '📋',
        preview: 'Form input group',
        defaultProps: {
          width: '100%',
          height: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: '8px',
          marginBottom: '16px',
        },
        children: [],
      },
      {
        id: 'modal',
        name: 'Modal',
        icon: '🪟',
        preview: 'Modal dialog',
        defaultProps: {
          width: '500px',
          height: 'auto',
          padding: '24px',
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          boxShadow: '0 10px 40px rgba(0, 0, 0, 0.2)',
          border: 'none',
        },
        children: [],
      },
      {
        id: 'dropdown',
        name: 'Dropdown',
        icon: '▼',
        preview: 'Dropdown component',
        defaultProps: {
          width: 'auto',
          height: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: '0',
          padding: '8px 0',
          backgroundColor: '#ffffff',
          borderRadius: '4px',
          boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
        },
        children: [],
      },
      {
        id: 'accordion',
        name: 'Accordion',
        icon: '📂',
        preview: 'Accordion component',
        defaultProps: {
          width: '100%',
          height: 'auto',
          border: '1px solid #e0e0e0',
          borderRadius: '4px',
        },
        children: [],
      },
    ],
  },
};

export const getComponentsByCategory = (category) => {
  return COMPONENT_LIBRARY[category]?.components || [];
};

export const getAllComponents = () => {
  const all = [];
  Object.values(COMPONENT_LIBRARY).forEach((cat) => {
    all.push(...cat.components);
  });
  return all;
};

export const getComponentTemplate = (componentId) => {
  for (const category of Object.values(COMPONENT_LIBRARY)) {
    const component = category.components.find((c) => c.id === componentId);
    if (component) return component;
  }
  return null;
};
