export const TEMPLATES = {
  dashboard: {
    name: 'Dashboard',
    icon: '📊',
    description: 'Professional analytics dashboard',
    components: [
      {
        id: 'navbar-dash',
        type: 'navbar',
        width: '100%',
        height: '64px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0 24px',
        backgroundColor: '#ffffff',
        borderBottom: '1px solid #e5e7eb',
        boxShadow: '0 2px 20px rgba(15, 23, 42, 0.04)',
        position: 'absolute',
        left: '0px',
        top: '0px',
      },
      {
        id: 'sidebar-dash',
        type: 'sidebar',
        width: '260px',
        height: 'calc(100vh - 64px)',
        display: 'flex',
        flexDirection: 'column',
        padding: '24px 16px',
        backgroundColor: '#f8fafc',
        borderRight: '1px solid #e5e7eb',
        position: 'absolute',
        left: '0px',
        top: '64px',
      },
      {
        id: 'main-dash',
        type: 'section',
        width: 'calc(100% - 260px)',
        height: 'calc(100vh - 64px)',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        padding: '32px',
        backgroundColor: '#f1f5f9',
        position: 'absolute',
        left: '260px',
        top: '64px',
      },
      {
        id: 'dashboard-heading',
        type: 'heading',
        text: 'Growth Overview',
        fontSize: '36px',
        fontWeight: '700',
        color: '#0f172a',
        marginBottom: '8px',
        width: '100%',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'dashboard-summary',
        type: 'paragraph',
        text: 'A smart dashboard layout with cards, analytics data, and activity panels.',
        fontSize: '16px',
        color: '#475569',
        width: '100%',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'stats-grid',
        type: 'grid',
        width: '100%',
        minHeight: '220px',
        display: 'grid',
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        gap: '16px',
        padding: '0',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'stats-card-1',
        type: 'card',
        width: '100%',
        height: '160px',
        padding: '20px',
        backgroundColor: '#ffffff',
        borderRadius: '18px',
        boxShadow: '0 12px 34px rgba(15, 23, 42, 0.05)',
        border: 'none',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'stats-card-2',
        type: 'card',
        width: '100%',
        height: '160px',
        padding: '20px',
        backgroundColor: '#ffffff',
        borderRadius: '18px',
        boxShadow: '0 12px 34px rgba(15, 23, 42, 0.05)',
        border: 'none',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'stats-card-3',
        type: 'card',
        width: '100%',
        height: '160px',
        padding: '20px',
        backgroundColor: '#ffffff',
        borderRadius: '18px',
        boxShadow: '0 12px 34px rgba(15, 23, 42, 0.05)',
        border: 'none',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
    ],
  },

  marketing: {
    name: 'Marketing Page',
    icon: '🚀',
    description: 'Landing-style hero, pricing, testimonials and contact sections',
    components: [
      {
        id: 'hero-banner',
        type: 'section',
        width: '100%',
        minHeight: '420px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        gap: '24px',
        padding: '80px 32px',
        backgroundColor: '#eef2ff',
        position: 'absolute',
        left: '0px',
        top: '0px',
      },
      {
        id: 'hero-title',
        type: 'heading',
        text: 'Launch faster with premium components',
        fontSize: '52px',
        fontWeight: '800',
        color: '#0f172a',
        width: '100%',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'hero-copy',
        type: 'paragraph',
        text: 'Build modern product pages and dashboards visually, with powerful automatic code generation.',
        fontSize: '18px',
        lineHeight: '1.75',
        color: '#475569',
        width: '100%',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'hero-action',
        type: 'button',
        text: 'Start Building',
        padding: '14px 28px',
        backgroundColor: '#4f46e5',
        color: '#ffffff',
        border: 'none',
        borderRadius: '999px',
        fontSize: '16px',
        fontWeight: '700',
        cursor: 'pointer',
        width: 'auto',
        position: 'relative',
        left: '0px',
        top: '0px',
      },
      {
        id: 'pricing-section',
        type: 'section',
        width: '100%',
        minHeight: '260px',
        display: 'grid',
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        gap: '18px',
        padding: '40px 32px',
        backgroundColor: '#ffffff',
        position: 'absolute',
        left: '0px',
        top: '480px',
      },
      {
        id: 'testimonial-block',
        type: 'card',
        width: '100%',
        padding: '24px',
        backgroundColor: '#f8fafc',
        borderRadius: '20px',
        boxShadow: '0 12px 30px rgba(15, 23, 42, 0.06)',
        position: 'absolute',
        left: '0px',
        top: '780px',
      },
      {
        id: 'contact-panel',
        type: 'section',
        width: '100%',
        minHeight: '260px',
        padding: '40px 32px',
        display: 'flex',
        flexDirection: 'column',
        gap: '18px',
        backgroundColor: '#eef2ff',
        position: 'absolute',
        left: '0px',
        top: '1060px',
      },
      {
        id: 'footer-marketing',
        type: 'footer',
        width: '100%',
        height: '120px',
        padding: '24px 32px',
        backgroundColor: '#0f172a',
        color: '#f8fafc',
        position: 'absolute',
        left: '0px',
        top: '1350px',
      },
    ],
  },
};

export const getTemplate = (templateId) => {
  return TEMPLATES[templateId];
};

export const getAllTemplates = () => {
  return Object.entries(TEMPLATES).map(([id, template]) => ({
    id,
    ...template,
  }));
};
