import ContainedButton from '../components/buttons/ContainedButton';
import ContainedDisabledButton from '../components/buttons/ContainedDisabledButton';
import ContainedLinkButton from '../components/buttons/ContainedLinkButton';
import OutlinedButton from '../components/buttons/OutlinedButton';
import OutlinedDisabledButton from '../components/buttons/OutlinedDisabledButton';
import OutlinedLinkButton from '../components/buttons/OutlinedLinkButton';
import ContainedIconButton from "../components/buttons/ContainedIconButton";
import DeleteIconButton from "../components/buttons/DeleteIconButton";
import AlarmIconButton from "../components/buttons/AlarmIconButton";
import ContainedButtonGroup from "../components/buttons/ContainedButtonGroup";
import OutlinedButtonGroup from "../components/buttons/OutlinedButtonGroup";
import TextButtonGroup from "../components/buttons/TextButtonGroup";

export const componentRegistry = {
  buttons: [
    {
      id: "contained-button-group",
      name: "Contained Button Group",
      category: 'buttons',
      icon: '🔘',
      description: 'Material UI Contained Button Group',
      component: ContainedButtonGroup,
      defaultProps: {
        firstText: "One",
        secondText: "Two",
        thirdText: "Three",
        color: "primary",
        size: "medium",
        orientation: "horizontal",
      },
      editableProps: ["firstText", "secondText", "thirdText", "color", "size", "orientation"],
      propTypes: {
        firstText: { type: 'string', label: 'Button 1 Text' },
        secondText: { type: 'string', label: 'Button 2 Text' },
        thirdText: { type: 'string', label: 'Button 3 Text' },
        color: { type: 'select', label: 'Color', options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'] },
        size: { type: 'select', label: 'Size', options: ['small', 'medium', 'large'] },
        orientation: { type: 'select', label: 'Orientation', options: ['horizontal', 'vertical'] },
      },
      draggable: true,
      droppable: false,
    },

    {
      id: "outlined-button-group",
      name: "Outlined Button Group",
      category: 'buttons',
      icon: '⬜',
      description: 'Material UI Outlined Button Group',
      component: OutlinedButtonGroup,
      defaultProps: {
        firstText: "One",
        secondText: "Two",
        thirdText: "Three",
        color: "primary",
        size: "medium",
        orientation: "horizontal",
      },
      editableProps: ["firstText", "secondText", "thirdText", "color", "size", "orientation"],
      propTypes: {
        firstText: { type: 'string', label: 'Button 1 Text' },
        secondText: { type: 'string', label: 'Button 2 Text' },
        thirdText: { type: 'string', label: 'Button 3 Text' },
        color: { type: 'select', label: 'Color', options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'] },
        size: { type: 'select', label: 'Size', options: ['small', 'medium', 'large'] },
        orientation: { type: 'select', label: 'Orientation', options: ['horizontal', 'vertical'] },
      },
      draggable: true,
      droppable: false,
    },

    {
      id: "text-button-group",
      name: "Text Button Group",
      category: 'buttons',
      icon: '📝',
      description: 'Material UI Text Button Group',
      component: TextButtonGroup,
      defaultProps: {
        firstText: "One",
        secondText: "Two",
        thirdText: "Three",
        color: "primary",
        size: "medium",
        orientation: "horizontal",
      },
      editableProps: ["firstText", "secondText", "thirdText", "color", "size", "orientation"],
      propTypes: {
        firstText: { type: 'string', label: 'Button 1 Text' },
        secondText: { type: 'string', label: 'Button 2 Text' },
        thirdText: { type: 'string', label: 'Button 3 Text' },
        color: { type: 'select', label: 'Color', options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'] },
        size: { type: 'select', label: 'Size', options: ['small', 'medium', 'large'] },
        orientation: { type: 'select', label: 'Orientation', options: ['horizontal', 'vertical'] },
      },
      draggable: true,
      droppable: false,
    },
    {
      id: 'contained-button',
      name: 'Contained Button',
      category: 'buttons',
      icon: '🔘',
      description: 'Material UI Contained Button - Primary action button',
      component: ContainedButton,
      
      defaultProps: {
        text: 'Contained Button',
        color: 'primary',
        size: 'medium',
        fullWidth: false,
        padding: '8px 16px',
        margin: '0px',
        fontSize: '14px',
        fontWeight: '600',
        border: 'none',
        borderRadius: '4px',
        backgroundColor: '',
        textColor: '',
        boxShadow: 'none',
      },

      editableProps: [
        'text',
        'color',
        'size',
        'fullWidth',
        'padding',
        'margin',
        'fontSize',
        'fontWeight',
        'border',
        'borderRadius',
        'backgroundColor',
        'textColor',
        'boxShadow',
      ],

      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        fullWidth: {
          type: 'boolean',
          label: 'Full Width',
          description: 'Make button full width',
        },
        padding: {
          type: 'string',
          label: 'Padding',
          description: 'Button padding (e.g., "8px 16px")',
        },
        margin: {
          type: 'string',
          label: 'Margin',
          description: 'Button margin (e.g., "0px" or "10px 5px")',
        },
        fontSize: {
          type: 'string',
          label: 'Font Size',
          description: 'Text size (e.g., "14px", "1rem")',
        },
        fontWeight: {
          type: 'select',
          label: 'Font Weight',
          options: ['300', '400', '500', '600', '700', '800', '900'],
          description: 'Text weight',
        },
        border: {
          type: 'string',
          label: 'Border',
          description: 'Border style (e.g., "1px solid #000")',
        },
        borderRadius: {
          type: 'string',
          label: 'Border Radius',
          description: 'Border radius (e.g., "4px", "8px")',
        },
        backgroundColor: {
          type: 'color',
          label: 'Background Color',
          description: 'Custom background color',
        },
        textColor: {
          type: 'color',
          label: 'Text Color',
          description: 'Custom text color',
        },
        boxShadow: {
          type: 'string',
          label: 'Box Shadow',
          description: 'Shadow effect (e.g., "0 2px 4px rgba(0,0,0,0.1)")',
        },
      },

      draggable: true,
      droppable: false,
    },

    {
      id: 'contained-disabled-button',
      name: 'Contained Disabled Button',
      category: 'buttons',
      icon: '🚫',
      description: 'Material UI Contained Button - Disabled state',
      component: ContainedDisabledButton,
      
      defaultProps: {
        text: 'Disabled Button',
        color: 'primary',
        size: 'medium',
        fullWidth: false,
        padding: '8px 16px',
        margin: '0px',
        fontSize: '14px',
        fontWeight: '600',
        border: 'none',
        borderRadius: '4px',
        backgroundColor: '',
        textColor: '',
        boxShadow: 'none',
      },

      editableProps: [
        'text',
        'color',
        'size',
        'fullWidth',
        'padding',
        'margin',
        'fontSize',
        'fontWeight',
        'border',
        'borderRadius',
        'backgroundColor',
        'textColor',
        'boxShadow',
      ],

      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        fullWidth: {
          type: 'boolean',
          label: 'Full Width',
          description: 'Make button full width',
        },
        padding: {
          type: 'string',
          label: 'Padding',
          description: 'Button padding (e.g., "8px 16px")',
        },
        margin: {
          type: 'string',
          label: 'Margin',
          description: 'Button margin (e.g., "0px" or "10px 5px")',
        },
        fontSize: {
          type: 'string',
          label: 'Font Size',
          description: 'Text size (e.g., "14px", "1rem")',
        },
        fontWeight: {
          type: 'select',
          label: 'Font Weight',
          options: ['300', '400', '500', '600', '700', '800', '900'],
          description: 'Text weight',
        },
        border: {
          type: 'string',
          label: 'Border',
          description: 'Border style (e.g., "1px solid #000")',
        },
        borderRadius: {
          type: 'string',
          label: 'Border Radius',
          description: 'Border radius (e.g., "4px", "8px")',
        },
        backgroundColor: {
          type: 'color',
          label: 'Background Color',
          description: 'Custom background color',
        },
        textColor: {
          type: 'color',
          label: 'Text Color',
          description: 'Custom text color',
        },
        boxShadow: {
          type: 'string',
          label: 'Box Shadow',
          description: 'Shadow effect (e.g., "0 2px 4px rgba(0,0,0,0.1)")',
        },
      },

      draggable: true,
      droppable: false,
    },

    {
      id: 'contained-link-button',
      name: 'Contained Link Button',
      category: 'buttons',
      icon: '🔗',
      description: 'Material UI Contained Button - Link variant',
      component: ContainedLinkButton,
      
      defaultProps: {
        text: 'Link Button',
        href: '#',
        color: 'primary',
        size: 'medium',
        fullWidth: false,
        padding: '8px 16px',
        margin: '0px',
        fontSize: '14px',
        fontWeight: '600',
        border: 'none',
        borderRadius: '4px',
        backgroundColor: '',
        textColor: '',
        boxShadow: 'none',
      },

      editableProps: [
        'text',
        'href',
        'color',
        'size',
        'fullWidth',
        'padding',
        'margin',
        'fontSize',
        'fontWeight',
        'border',
        'borderRadius',
        'backgroundColor',
        'textColor',
        'boxShadow',
      ],

      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        href: {
          type: 'string',
          label: 'Link URL',
          description: 'URL for the link button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        fullWidth: {
          type: 'boolean',
          label: 'Full Width',
          description: 'Make button full width',
        },
        padding: {
          type: 'string',
          label: 'Padding',
          description: 'Button padding (e.g., "8px 16px")',
        },
        margin: {
          type: 'string',
          label: 'Margin',
          description: 'Button margin (e.g., "0px" or "10px 5px")',
        },
        fontSize: {
          type: 'string',
          label: 'Font Size',
          description: 'Text size (e.g., "14px", "1rem")',
        },
        fontWeight: {
          type: 'select',
          label: 'Font Weight',
          options: ['300', '400', '500', '600', '700', '800', '900'],
          description: 'Text weight',
        },
        border: {
          type: 'string',
          label: 'Border',
          description: 'Border style (e.g., "1px solid #000")',
        },
        borderRadius: {
          type: 'string',
          label: 'Border Radius',
          description: 'Border radius (e.g., "4px", "8px")',
        },
        backgroundColor: {
          type: 'color',
          label: 'Background Color',
          description: 'Custom background color',
        },
        textColor: {
          type: 'color',
          label: 'Text Color',
          description: 'Custom text color',
        },
        boxShadow: {
          type: 'string',
          label: 'Box Shadow',
          description: 'Shadow effect (e.g., "0 2px 4px rgba(0,0,0,0.1)")',
        },
      },

      draggable: true,
      droppable: false,
    },

    {
      id: 'outlined-button',
      name: 'Outlined Button',
      category: 'buttons',
      icon: '⬜',
      description: 'Material UI Outlined Button - Secondary action button',
      component: OutlinedButton,

      defaultProps: {
        text: 'Outlined Button',
        color: 'primary',
        size: 'medium',
        fullWidth: false,
        padding: '8px 16px',
        margin: '0px',
        fontSize: '14px',
        fontWeight: '600',
        border: '1px solid',
        borderRadius: '4px',
        backgroundColor: '',
        textColor: '',
        boxShadow: 'none',
      },

      editableProps: [
        'text',
        'color',
        'size',
        'fullWidth',
        'padding',
        'margin',
        'fontSize',
        'fontWeight',
        'border',
        'borderRadius',
        'backgroundColor',
        'textColor',
        'boxShadow',
      ],

      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        fullWidth: {
          type: 'boolean',
          label: 'Full Width',
          description: 'Make button full width',
        },
        padding: {
          type: 'string',
          label: 'Padding',
          description: 'Button padding (e.g., "8px 16px")',
        },
        margin: {
          type: 'string',
          label: 'Margin',
          description: 'Button margin (e.g., "0px" or "10px 5px")',
        },
        fontSize: {
          type: 'string',
          label: 'Font Size',
          description: 'Text size (e.g., "14px", "1rem")',
        },
        fontWeight: {
          type: 'select',
          label: 'Font Weight',
          options: ['300', '400', '500', '600', '700', '800', '900'],
          description: 'Text weight',
        },
        border: {
          type: 'string',
          label: 'Border',
          description: 'Border style (e.g., "1px solid #000")',
        },
        borderRadius: {
          type: 'string',
          label: 'Border Radius',
          description: 'Border radius (e.g., "4px", "8px")',
        },
        backgroundColor: {
          type: 'color',
          label: 'Background Color',
          description: 'Custom background color',
        },
        textColor: {
          type: 'color',
          label: 'Text Color',
          description: 'Custom text color',
        },
        boxShadow: {
          type: 'string',
          label: 'Box Shadow',
          description: 'Shadow effect (e.g., "0 2px 4px rgba(0,0,0,0.1)")',
        },
      },

      draggable: true,
      droppable: false,
    },

    {
      id: 'outlined-disabled-button',
      name: 'Outlined Disabled Button',
      category: 'buttons',
      icon: '⛔',
      description: 'Material UI Outlined Button - Disabled state',
      component: OutlinedDisabledButton,

      defaultProps: {
        text: 'Disabled Button',
        color: 'primary',
        size: 'medium',
        fullWidth: false,
        padding: '8px 16px',
        margin: '0px',
        fontSize: '14px',
        fontWeight: '600',
        border: '1px solid',
        borderRadius: '4px',
        backgroundColor: '',
        textColor: '',
        boxShadow: 'none',
      },

      editableProps: [
        'text',
        'color',
        'size',
        'fullWidth',
        'padding',
        'margin',
        'fontSize',
        'fontWeight',
        'border',
        'borderRadius',
        'backgroundColor',
        'textColor',
        'boxShadow',
      ],

      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        fullWidth: {
          type: 'boolean',
          label: 'Full Width',
          description: 'Make button full width',
        },
        padding: {
          type: 'string',
          label: 'Padding',
          description: 'Button padding (e.g., "8px 16px")',
        },
        margin: {
          type: 'string',
          label: 'Margin',
          description: 'Button margin (e.g., "0px" or "10px 5px")',
        },
        fontSize: {
          type: 'string',
          label: 'Font Size',
          description: 'Text size (e.g., "14px", "1rem")',
        },
        fontWeight: {
          type: 'select',
          label: 'Font Weight',
          options: ['300', '400', '500', '600', '700', '800', '900'],
          description: 'Text weight',
        },
        border: {
          type: 'string',
          label: 'Border',
          description: 'Border style (e.g., "1px solid #000")',
        },
        borderRadius: {
          type: 'string',
          label: 'Border Radius',
          description: 'Border radius (e.g., "4px", "8px")',
        },
        backgroundColor: {
          type: 'color',
          label: 'Background Color',
          description: 'Custom background color',
        },
        textColor: {
          type: 'color',
          label: 'Text Color',
          description: 'Custom text color',
        },
        boxShadow: {
          type: 'string',
          label: 'Box Shadow',
          description: 'Shadow effect (e.g., "0 2px 4px rgba(0,0,0,0.1)")',
        },
      },

      draggable: true,
      droppable: false,
    },

    {
      id: 'outlined-link-button',
      name: 'Outlined Link Button',
      category: 'buttons',
      icon: '🌐',
      description: 'Material UI Outlined Button - Link variant',
      component: OutlinedLinkButton,

      defaultProps: {
        text: 'Link Button',
        href: '#',
        color: 'primary',
        size: 'medium',
        fullWidth: false,
        padding: '8px 16px',
        margin: '0px',
        fontSize: '14px',
        fontWeight: '600',
        border: '1px solid',
        borderRadius: '4px',
        backgroundColor: '',
        textColor: '',
        boxShadow: 'none',
      },

      editableProps: [
        'text',
        'href',
        'color',
        'size',
        'fullWidth',
        'padding',
        'margin',
        'fontSize',
        'fontWeight',
        'border',
        'borderRadius',
        'backgroundColor',
        'textColor',
        'boxShadow',
      ],

      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        href: {
          type: 'string',
          label: 'Link URL',
          description: 'URL for the link button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        fullWidth: {
          type: 'boolean',
          label: 'Full Width',
          description: 'Make button full width',
        },
        padding: {
          type: 'string',
          label: 'Padding',
          description: 'Button padding (e.g., "8px 16px")',
        },
        margin: {
          type: 'string',
          label: 'Margin',
          description: 'Button margin (e.g., "0px" or "10px 5px")',
        },
        fontSize: {
          type: 'string',
          label: 'Font Size',
          description: 'Text size (e.g., "14px", "1rem")',
        },
        fontWeight: {
          type: 'select',
          label: 'Font Weight',
          options: ['300', '400', '500', '600', '700', '800', '900'],
          description: 'Text weight',
        },
        border: {
          type: 'string',
          label: 'Border',
          description: 'Border style (e.g., "1px solid #000")',
        },
        borderRadius: {
          type: 'string',
          label: 'Border Radius',
          description: 'Border radius (e.g., "4px", "8px")',
        },
        backgroundColor: {
          type: 'color',
          label: 'Background Color',
          description: 'Custom background color',
        },
        textColor: {
          type: 'color',
          label: 'Text Color',
          description: 'Custom text color',
        },
        boxShadow: {
          type: 'string',
          label: 'Box Shadow',
          description: 'Shadow effect (e.g., "0 2px 4px rgba(0,0,0,0.1)")',
        },
      },

      draggable: true,
      droppable: false,
    },
    {
      id: "contained-icon-button",
      name: "Contained Icon Button",
      category: 'buttons',
      icon: '✉️',
      description: 'Material UI Contained Icon Button with Send icon',
      component: ContainedIconButton,
      defaultProps: {
        text: "Send",
        color: "primary",
        size: "medium",
        fullWidth: false,
      },
      editableProps: [
        "text",
        "color",
        "size",
        "fullWidth",
      ],
      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        fullWidth: {
          type: 'boolean',
          label: 'Full Width',
          description: 'Make button full width',
        },
      },
    },
    {
      id: "delete-icon-button",
      name: "Delete Icon Button",
      category: 'buttons',
      icon: '🗑️',
      description: 'Material UI Delete Icon Button with Delete icon',
      component: DeleteIconButton,
      defaultProps: {
        text: "Delete",
        color: "error",
        size: "medium",
        disabled: false,
      },
      editableProps: [
        "text",
        "color",
        "size",
        "disabled",
      ],
      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['default', 'primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        disabled: {
          type: 'boolean',
          label: 'Disabled',
          description: 'Disable the button',
        },
      },
    },
    {
      id: "alarm-icon-button",
      name: "Alarm Icon Button",
      category: 'buttons',
      icon: '🔔',
      description: 'Material UI Alarm Icon Button with Notification icon',
      component: AlarmIconButton,
      defaultProps: {
        text: "Alarm",
        color: "warning",
        size: "medium",
        disabled: false,
      },
      editableProps: [
        "text",
        "color",
        "size",
        "disabled",
      ],
      propTypes: {
        text: {
          type: 'string',
          label: 'Button Text',
          description: 'Text displayed on the button',
        },
        color: {
          type: 'select',
          label: 'Color',
          options: ['default', 'primary', 'secondary', 'success', 'error', 'warning', 'info'],
          description: 'Button color variant',
        },
        size: {
          type: 'select',
          label: 'Size',
          options: ['small', 'medium', 'large'],
          description: 'Button size',
        },
        disabled: {
          type: 'boolean',
          label: 'Disabled',
          description: 'Disable the button',
        },
      },
    },
  ],
};
